/**
 * onTaskClient
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/WorkflowGraphTask'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./WorkflowGraphTask'));
  } else {
    // Browser globals (root is window)
    if (!root.OnTaskClient) {
      root.OnTaskClient = {};
    }
    root.OnTaskClient.WorkflowGraph = factory(root.OnTaskClient.ApiClient, root.OnTaskClient.WorkflowGraphTask);
  }
}(this, function(ApiClient, WorkflowGraphTask) {
  'use strict';




  /**
   * The WorkflowGraph model module.
   * @module model/WorkflowGraph
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>WorkflowGraph</code>.
   * @alias module:model/WorkflowGraph
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>WorkflowGraph</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkflowGraph} obj Optional instance to populate.
   * @return {module:model/WorkflowGraph} The populated <code>WorkflowGraph</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('friendlyName')) {
        obj['friendlyName'] = ApiClient.convertToType(data['friendlyName'], 'String');
      }
      if (data.hasOwnProperty('injectableName')) {
        obj['injectableName'] = ApiClient.convertToType(data['injectableName'], 'String');
      }
      if (data.hasOwnProperty('options')) {
        obj['options'] = ApiClient.convertToType(data['options'], Object);
      }
      if (data.hasOwnProperty('tasks')) {
        obj['tasks'] = ApiClient.convertToType(data['tasks'], [WorkflowGraphTask]);
      }
    }
    return obj;
  }

  /**
   * @member {String} friendlyName
   */
  exports.prototype['friendlyName'] = undefined;
  /**
   * @member {String} injectableName
   */
  exports.prototype['injectableName'] = undefined;
  /**
   * @member {Object} options
   */
  exports.prototype['options'] = undefined;
  /**
   * @member {Array.<module:model/WorkflowGraphTask>} tasks
   */
  exports.prototype['tasks'] = undefined;



  return exports;
}));


