/**
 * onTaskClient
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OnTaskClient);
  }
}(this, function(expect, OnTaskClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OnTaskClient.TasksApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TasksApi', function() {
    describe('getBootstrap', function() {
      it('should call getBootstrap successfully', function(done) {
        //uncomment below and update the code to test getBootstrap
        //instance.getBootstrap(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTasksById', function() {
      it('should call getTasksById successfully', function(done) {
        //uncomment below and update the code to test getTasksById
        //instance.getTasksById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTaskById', function() {
      it('should call postTaskById successfully', function(done) {
        //uncomment below and update the code to test postTaskById
        //instance.postTaskById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workflowsDeleteTasksByName', function() {
      it('should call workflowsDeleteTasksByName successfully', function(done) {
        //uncomment below and update the code to test workflowsDeleteTasksByName
        //instance.workflowsDeleteTasksByName(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workflowsGetAllTasks', function() {
      it('should call workflowsGetAllTasks successfully', function(done) {
        //uncomment below and update the code to test workflowsGetAllTasks
        //instance.workflowsGetAllTasks(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workflowsGetTasksByName', function() {
      it('should call workflowsGetTasksByName successfully', function(done) {
        //uncomment below and update the code to test workflowsGetTasksByName
        //instance.workflowsGetTasksByName(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('workflowsPutTask', function() {
      it('should call workflowsPutTask successfully', function(done) {
        //uncomment below and update the code to test workflowsPutTask
        //instance.workflowsPutTask(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
